/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_intLiteral = 1,
  sym_floatLiteral = 2,
  anon_sym_SQUOTE = 3,
  anon_sym_DQUOTE = 4,
  sym_char = 5,
  sym_identifier = 6,
  sym__SPACE = 7,
  anon_sym_LF = 8,
  sym_source_file = 9,
  sym__expr = 10,
  sym_call = 11,
  sym_charLiteral = 12,
  sym_stringLiteral = 13,
  sym__newStatement = 14,
  aux_sym_source_file_repeat1 = 15,
  aux_sym_stringLiteral_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_intLiteral] = "intLiteral",
  [sym_floatLiteral] = "floatLiteral",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_char] = "char",
  [sym_identifier] = "identifier",
  [sym__SPACE] = "_SPACE",
  [anon_sym_LF] = "\n",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_call] = "call",
  [sym_charLiteral] = "charLiteral",
  [sym_stringLiteral] = "stringLiteral",
  [sym__newStatement] = "_newStatement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_stringLiteral_repeat1] = "stringLiteral_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_intLiteral] = sym_intLiteral,
  [sym_floatLiteral] = sym_floatLiteral,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_char] = sym_char,
  [sym_identifier] = sym_identifier,
  [sym__SPACE] = sym__SPACE,
  [anon_sym_LF] = anon_sym_LF,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_call] = sym_call,
  [sym_charLiteral] = sym_charLiteral,
  [sym_stringLiteral] = sym_stringLiteral,
  [sym__newStatement] = sym__newStatement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_stringLiteral_repeat1] = aux_sym_stringLiteral_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_intLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_floatLiteral] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__SPACE] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_charLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_stringLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym__newStatement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stringLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(12);
      END_STATE();
    case 4:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_intLiteral);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_intLiteral);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_floatLiteral);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '\n') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__SPACE);
      if (lookahead == '\n') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_intLiteral] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym__SPACE] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__expr] = STATE(2),
    [sym_call] = STATE(2),
    [sym_charLiteral] = STATE(2),
    [sym_stringLiteral] = STATE(2),
    [sym_intLiteral] = ACTIONS(5),
    [sym_floatLiteral] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_identifier] = ACTIONS(7),
    [sym__SPACE] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__expr] = STATE(3),
    [sym_call] = STATE(3),
    [sym_charLiteral] = STATE(3),
    [sym_stringLiteral] = STATE(3),
    [sym__newStatement] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_intLiteral] = ACTIONS(17),
    [sym_floatLiteral] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_identifier] = ACTIONS(19),
    [sym__SPACE] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym__expr] = STATE(3),
    [sym_call] = STATE(3),
    [sym_charLiteral] = STATE(3),
    [sym_stringLiteral] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_intLiteral] = ACTIONS(25),
    [sym_floatLiteral] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_identifier] = ACTIONS(23),
    [sym__SPACE] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym__expr] = STATE(5),
    [sym_call] = STATE(5),
    [sym_charLiteral] = STATE(5),
    [sym_stringLiteral] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_intLiteral] = ACTIONS(29),
    [sym_floatLiteral] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_identifier] = ACTIONS(31),
    [sym__SPACE] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(33),
  },
  [STATE(5)] = {
    [sym__expr] = STATE(3),
    [sym_call] = STATE(3),
    [sym_charLiteral] = STATE(3),
    [sym_stringLiteral] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_intLiteral] = ACTIONS(17),
    [sym_floatLiteral] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_identifier] = ACTIONS(19),
    [sym__SPACE] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(41), 2,
      sym_intLiteral,
      anon_sym_LF,
    ACTIONS(39), 5,
      ts_builtin_sym_end,
      sym_floatLiteral,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_identifier,
  [15] = 3,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(45), 2,
      sym_intLiteral,
      anon_sym_LF,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      sym_floatLiteral,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_identifier,
  [30] = 3,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(49), 2,
      sym_intLiteral,
      anon_sym_LF,
    ACTIONS(47), 5,
      ts_builtin_sym_end,
      sym_floatLiteral,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_identifier,
  [45] = 5,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym__newStatement,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
  [61] = 5,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_LF,
    STATE(4), 1,
      sym__newStatement,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
  [77] = 4,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      sym_char,
    STATE(12), 1,
      aux_sym_stringLiteral_repeat1,
  [90] = 4,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(62), 1,
      sym_char,
    STATE(13), 1,
      aux_sym_stringLiteral_repeat1,
  [103] = 4,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      sym_char,
    STATE(13), 1,
      aux_sym_stringLiteral_repeat1,
  [116] = 2,
    ACTIONS(3), 1,
      sym__SPACE,
    ACTIONS(69), 1,
      sym_char,
  [123] = 2,
    ACTIONS(13), 1,
      sym__SPACE,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [130] = 2,
    ACTIONS(13), 1,
      sym__SPACE,
    ACTIONS(73), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 15,
  [SMALL_STATE(8)] = 30,
  [SMALL_STATE(9)] = 45,
  [SMALL_STATE(10)] = 61,
  [SMALL_STATE(11)] = 77,
  [SMALL_STATE(12)] = 90,
  [SMALL_STATE(13)] = 103,
  [SMALL_STATE(14)] = 116,
  [SMALL_STATE(15)] = 123,
  [SMALL_STATE(16)] = 130,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_charLiteral, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_charLiteral, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stringLiteral_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_stringLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_imp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "imp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
